export const ALL_CATE_REQUEST = "ALL_CATE_REQUEST";
export const ALL_CATE_SUCCESS = "ALL_CATE_SUCCESS";
export const ALL_CATE_FAIL = "ALL_CATE_FAIL";

export const SINGLE_CATE_REQUEST = "SINGLE_CATE_REQUEST";
export const SINGLE_CATE_SUCCESS = "SINGLE_CATE_SUCCESS";
export const SINGLE_CATE_FAIL = "SINGLE_CATE_FAIL";

export const CREATE_CATE_REQUEST = "CREATE_CATE_REQUEST";
export const CREATE_CATE_SUCCESS = "CREATE_CATE_SUCCESS";
export const CREATE_CATE_FAIL = "CREATE_CATE_FAIL";
export const CREATE_CATE_RESET = "CREATE_CATE_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_CATE_REQUEST = "UPDATE_CATE_REQUEST";
export const UPDATE_CATE_SUCCESS = "UPDATE_CATE_SUCCESS";
export const UPDATE_CATE_RESET = "UPDATE_CATE_RESET";
export const UPDATE_CATE_FAIL = "UPDATE_CATE_FAIL";

export const DELETE_CATE_REQUEST = "DELETE_CATE_REQUEST";
export const DELETE_CATE_SUCCESS = "DELETE_CATE_SUCCESS";
export const DELETE_CATE_FAIL = "DELETE_CATE_FAIL";
export const DELETE_CATE_RESET = "DELETE_CATE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
